### ISSUE TITLE
Cannot ask multiple times to register an account

### ISSUE THREAD

**Issue by ghost** [Norbert-Waszkowiak-WAT/ppz-yapmasters#3]
Z tego co widzę, nie mogę kliknąć kilka razy rejestruj. Według mnie, powinno dać się kilka razy to zrobić, by dostać np. kod weryfikujący jeszcze raz (dla użytkowników niepełnosprytnych).

Według mnie, przy sytuacji ponownej rejestracji, serwer powinien wysłać znowu kod weryfikujący (ewentualnie przyjąć nowe dane, np. nowe hasło lub username). W tej chwili, serwer zwraca po prostu kod 500 z wiadomością "Internal Server Error", więc taka sytuacja nie jest brana pod uwagę.

```
[Nest] 11895  - 14.12.2024, 13:50:17   ERROR [ExceptionsHandler] E11000 duplicate key error collection: nest.users index: email_1_username_1 dup key: { email: "elogaming987@gmail.com", username: "example" }
MongoServerError: E11000 duplicate key error collection: nest.users index: email_1_username_1 dup key: { email: "elogaming987@gmail.com", username: "example" }
```

**Comment by LonleySailor** [comment]
Uywaj branch master do logowania sie
