### ISSUE TITLE
Ponowne wysyłanie kodu weryfikacyjnego

### ISSUE THREAD

**Issue by ghost** [Norbert-Waszkowiak-WAT/ppz-yapmasters#4]
Gdy kod jest wysyłany ponownie, serwer wysyła maila w zacytowany sposób, więc w aplikacji, mail nie pokazuje od razu zawartości.

**Comment by LonleySailor** [comment]
Możesz dokładniej wytłumaczyć bo nierozumiem w czy jest problem

**Comment by ghost** [comment]
![Screenshot_20241214_140318_Gmail.png](https://github.com/user-attachments/assets/9a62fda1-a948-4566-a206-0ae1bfeebbee)

By otworzyć maila, niestety muszę nacisnąć na "pokaż cytowany tekst" który nie powinien w tym przypadku istnieć. Chyba że Gmail coś kręci

**Comment by ghost** [comment]
![Screenshot_20241214_140515_Gmail.png](https://github.com/user-attachments/assets/df964c9d-3c3f-4c7e-82bd-dd5e4bfdcbc3)

Interesujące, za trzecim i czwartym razem, widzę cytowanie tekstu w środku maila.

**Comment by ghost** [comment]
Jak coś, pierwszy mail wygląda normalnie, kolejne się walą

**Comment by LonleySailor** [comment]
Gmail skill issue
